version: '2'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab'
    container_name: gitlab
    depends_on:
     - redis
     - postgresql
     - gitlab-runner
     - gitlab-runner_d
    networks:
      docker_nt:
        ipv4_address: 172.28.0.5
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://domain_gitlab'
        nginx['enable'] = false
        web_server['external_users'] = ['www-data']
        gitlab_workhorse['listen_network'] = "tcp"
        gitlab_workhorse['listen_addr'] = "0.0.0.0:8181"
        gitlab_rails['gitlab_shell_ssh_port'] = 10022
        postgresql['enable'] = false
        gitlab_rails['db_adapter'] = "postgresql"
        gitlab_rails['db_database'] = "gitlabhq_production"
        gitlab_rails['db_username'] = "git"
        gitlab_rails['db_password'] = "Password"
        gitlab_rails['db_host'] = "postgresql"
        gitlab_rails['db_port'] = 5432
        redis['enable'] = false
        gitlab_rails['redis_host'] = "redis"
        gitlab_rails['redis_port'] = 6379
        gitlab_rails['redis_database'] = 0
        registry_external_url 'https://registry_url'
        registry_nginx['enable'] = false
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_issuer'] = "omnibus-gitlab-issuer"
        registry['registry_http_addr'] = "registry_url:5000"
    ports:
      - '10022:22'
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./letsencrypt:/etc/gitlab/ssl/
  nginx:
    container_name: nginx
    image: nginx:1.15.0-alpine
    restart: always
    links:
      - gitlab:gitlab
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./letsencrypt/:/etc/letsencrypt
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/www:/var/www
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      docker_nt:
        ipv4_address: 172.28.0.3


  postgresql:
    container_name: postgresql
    restart: always
    image: postgres:9.6.2-alpine
    volumes:
    - ./postgresql:/var/lib/postgresql:Z
    environment:
    - POSTGRES_USER=git
    - POSTGRES_PASSWORD=Password
    - POSTGRES_DB=gitlabhq_production
    - POSTGRES_EXTENSION=pg_trgm
    networks:
      docker_nt:
        ipv4_address: 172.28.0.7


  redis:
    restart: always
    image: redis:latest
    container_name: redis
    volumes:
     - "./redis:/data"
    networks:
      docker_nt:
        ipv4_address: 172.28.0.6

  
  gitlab-runner:
      image: gitlab/gitlab-runner
      container_name: gitlab-runner
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./runner/conf:/etc/gitlab-runner
      restart: always
      networks:
        docker_nt:
          ipv4_address: 172.28.0.2

  gitlab-runner_d:
      image: gitlab/gitlab-runner
      container_name: gitlab-runner_d
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./runner_d/conf:/etc/gitlab-runner
      restart: always
      networks:
        docker_nt:
          ipv4_address: 172.28.0.4

  registry:
    container_name: hostname_domain_registry
    restart: always
    image: registry:2.4.1
    depends_on: 
      - gitlab
    networks:
      docker_nt:
        ipv4_address: 172.28.0.8
    environment:
      VIRTUAL_HOST: hostname_domain_registry
      # Tells nginx proxy to forward on port 5000
      # and get a clean and nice registry URL
      VIRTUAL_PORT: 5000
      REGISTRY_LOG_LEVEL: info
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry
      REGISTRY_AUTH_TOKEN_REALM: https://domain-gitlab/jwt/auth
      REGISTRY_AUTH_TOKEN_SERVICE: container_registry
      REGISTRY_AUTH_TOKEN_ISSUER: omnibus-gitlab-issuer
      #gitlab/data/registry/gitlab-registry.crt:
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/gitlab-registry.crt
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      #REGISTRY_AUTH: htpasswd
      #REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      #REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    
    volumes:
      - ./registry/data:/registry
      - ./registry/gitlab-registry.crt:/certs/gitlab-registry.crt
     # - ./registry/auth:/auth

networks:
  docker_nt:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
    
